### ISSUE TITLE
Setting up the Kanban board

### ISSUE THREAD

**Issue by Sboursen** [Sboursen/MV-Module2-capstone#21]
### Hello :wave: 

Here is the link to the Github project: [Link](https://github.com/Sboursen/MV-Module2-capstone/projects/1).
**We are three teammates**

**Comment by SajjadAhmad14** [comment]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi team, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
