### ISSUE TITLE
Morning session: Peer-to-peer code review -- 10th MAR 2022

### ISSUE THREAD

**Issue by Sboursen** [Sboursen/MV-Module2-capstone#34]
## Hi @jerryowusu  , :wave: 

**Good work implementing the Display-reservations-pop-up feature.**
However, we suggest implementing the following modification:

- [ ] Please Move the year to the space under the horsepower.
![issue](https://user-images.githubusercontent.com/51741471/157611176-1917e28f-0bf2-448a-bee8-31a0eb993005.png)

- [ ] You can also try to have a good structure of the popup like it shown in the requirements:
![image](https://user-images.githubusercontent.com/51741471/157611337-02ffec6d-120b-4463-8978-eed030279f0c.png)

Please feel free to ask for any more clarification about the issues we raised.
Happy Coding! :rocket:

**Comment by jerryowusu** [comment]
Thanks @Sboursen for drawing my attention. It has been resolved as discussed. Thanks again
